spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/assignment
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 6379

server:
  port: 8080